import { sql } from "drizzle-orm";
import { dbV8 } from "../legacy/v8/db/client.ts";
import { V8_DB_SCHEMA } from "../legacy/v8/db/schema.ts";

const schemaName = V8_DB_SCHEMA.replace(/"/g, "");

async function setupV8Schema(): Promise<void> {
  await dbV8.execute(sql.raw(`create schema if not exists "${schemaName}"`));

  await dbV8.execute(
    sql.raw(`
    create table if not exists "${schemaName}"."users" (
      "id" integer generated by default as identity primary key,
      "email" text not null,
      "name" text not null,
      "password" text not null,
      "created_at" timestamptz not null default now()
    );
  `),
  );

  await dbV8.execute(
    sql.raw(`
    create unique index if not exists "v8_users_email_idx" on "${schemaName}"."users"("email");
  `),
  );

  await dbV8.execute(
    sql.raw(`
    create table if not exists "${schemaName}"."menu_items" (
      "id" integer generated by default as identity primary key,
      "name" text not null,
      "price" integer not null,
      "category" text not null,
      "description" text not null,
      "image_url" text not null
    );
  `),
  );

  await dbV8.execute(
    sql.raw(`
    create table if not exists "${schemaName}"."orders" (
      "id" integer generated by default as identity primary key,
      "user_id" integer not null references "${schemaName}"."users"("id"),
      "total" integer not null default 0,
      "status" text not null default 'pending',
      "created_at" timestamptz not null default now(),
      "submitted_at" timestamptz
    );
  `),
  );

  await dbV8.execute(
    sql.raw(`
    create index if not exists "v8_orders_user_id_idx" on "${schemaName}"."orders"("user_id");
  `),
  );

  await dbV8.execute(
    sql.raw(`
    create table if not exists "${schemaName}"."order_items" (
      "id" integer generated by default as identity primary key,
      "order_id" integer not null references "${schemaName}"."orders"("id") on delete cascade,
      "item_id" integer not null,
      "name" text not null,
      "price" integer not null,
      "category" text not null,
      "description" text not null,
      "image_url" text not null,
      "qty" integer not null
    );
  `),
  );

  await dbV8.execute(
    sql.raw(`
    create unique index if not exists "v8_order_items_order_item_idx"
    on "${schemaName}"."order_items"("order_id", "item_id");
  `),
  );

  console.log(`V8 legacy schema is ready: ${schemaName}`);
}

setupV8Schema().catch((error) => {
  console.error("Failed to setup V8 legacy schema", error);
  process.exit(1);
});
